# Generated by Django 3.2.6 on 2021-08-03 18:42

from django.db import migrations, models
import django.db.models.deletion
import documents.uploaders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_unique_together'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150, null=True)),
                ('reason', models.TextField(max_length=200)),
                ('visit_date', models.DateField()),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to=documents.uploaders.prescription_img_uploader)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
    ]
