# Generated by Django 3.2.6 on 2021-08-04 06:12

from django.db import migrations, models
import django.db.models.deletion
import documents.uploaders


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_unique_together'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('sonography', 'sonography'), ('test', 'test'), ('image-scan', 'image-scan'), ('other', 'other')], max_length=10)),
                ('doc_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.uploaders.document_img_uploader)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='patients.patient')),
            ],
        ),
    ]
