# Generated by Django 3.2.6 on 2021-08-02 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('user', 'name')},
        ),
    ]
