# Generated by Django 3.2.6 on 2021-08-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file_no', models.IntegerField(blank=True, null=True)),
                ('clinic_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='patients.patient')),
            ],
            options={
                'unique_together': {('name', 'patient')},
            },
        ),
    ]
