# Generated by Django 3.2.6 on 2021-08-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
    ]
